API_KEY="AIzaSyAgT26vVoJnpjwmkoNaDl1Aj3NezOlSpKs"
pdfcrowduser="agaviriaj"
pdfcrowdpass="ff60721e6cd397590c07eca9d5d71f0b"

user_appraisal= "buydepa"
password_appraisal= "GWc42X887heD"
host_appraisal= "buydepa-market.cy47rcxrw2g5.us-east-1.rds.amazonaws.com"
schema_appraisal= "appraisal"

user_bigdata="admin"
password_bigdata="Aa12345678"
host_bigdata="data-proyect.cbpqfqlu2upq.us-east-2.rds.amazonaws.com"
schema_bigdata="bigdata"
    
user_market= "buydepa"
password_market= "GWc42X887heD"
host_market= "buydepa-market.cy47rcxrw2g5.us-east-1.rds.amazonaws.com"
schema_market= "market"

user_colombia="admin"
password_colombia="testBuydepa1!"
host_colombia="buydepa-market-dev2.cy47rcxrw2g5.us-east-1.rds.amazonaws.com"
schema_colombia="colombia"